--- #YAML:1.0
name:               WebDyne-Template
version:            1.018
abstract:           ~
author:
    - Andrew Speer <andrew@webdyne.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    WebDyne::Chain:  ~
resources:
    homepage:  http://webdyne.org
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
